### ISSUE TITLE
Password Fehler (als Password Feld verschwindet die Eingabe)

### ISSUE THREAD

**Issue by TomasiDeveloping** [iobroker-community-adapters/ioBroker.synology#11]
**Describe the bug**  
Input field for password disappears and it is not possible to enter a password. With copy paste of the password I get in the log of Synology that the user fails to login.
Thus, the password is also not stored correctly.

**To Reproduce**  
1. Go to 'Adapter instance settings'
2. Click on 'Password input field'

**Expected behavior**  
Entering a password

**Versions:**  
 - Adapter version: v1.1.2
 - JS-Controller version: 3.3.15
 - Node version: v12.22.4
 - Operating system:  Linux -> RP4

**Comment by stephan1827** [comment]
I have the same issue, could this be an issue of the new admin adapter 5.1.23?

**Comment by lobomau76** [comment]
Same problem here

Versions:

Adapter version: v1.1.2
JS-Controller version: 3.3.15
Node version: v12.22.4
Admin Adapter: 5.1.23
Operating system: Linux

**Comment by TomasiDeveloping** [comment]
If I change the Admin Adapter to "Old User Interface" it is possible to enter the password in the Synology Adapter but it remains yellow and in the Synology log I see that the user fails to login.

**Comment by stephan1827** [comment]
Are there any new information on this issue?

**Comment by Apollon77** [comment]
As soon as someone finds time we will check it ... The workaround is told above

**Comment by TomasiDeveloping** [comment]
The workaround only fixes the disappearance of the input for me.
When I set the password I see in the Synology log that the user of ioBroker can not log in. (Password or username wrong).
Can someone log in with the workaround or same problem as me ?

**Comment by Apollon77** [comment]
@MeisterTR any idea?

**Comment by MeisterTR** [comment]
@TomasiDeveloping can you post a screenshot

**Comment by TomasiDeveloping** [comment]
@MeisterTR What exactly do you need a screenshot of ?

**Comment by MeisterTR** [comment]
thats a bug from admin adaper: config :

```
        "password": {
            "type": "password",
            "label": "Password",
            "sm": 12,
            "md": 4,
            "lg": 3
        },
```

**Comment by MeisterTR** [comment]
Created an issue https://github.com/ioBroker/ioBroker.admin/issues/1131

**Comment by MeisterTR** [comment]
Workaround: Copy password from clipboard should work

**Comment by TomasiDeveloping** [comment]
For me, the only way to set the password or copy paste is to set the Admin Adapter to "Old User Interface".
But the login is still incorrect.

Synology Login via the user interface:
![loginDSM](https://user-images.githubusercontent.com/67390491/130561094-ee39ad7a-a2b7-4800-a980-5f968d920b79.png)


ioBroker Log:
![ioBrokerLog](https://user-images.githubusercontent.com/67390491/130561131-0f20e7af-9601-47f4-92a7-536fbabfdc9c.png)


Synology Log:
![synoLog](https://user-images.githubusercontent.com/67390491/130561152-9a893475-eef4-406c-8059-9416005ff920.png)

**Comment by Ricox1975** [comment]
Gibt's hier schon Neuigkeiten zu vermelden?
Nach heutigem Upgrade auf 1.1.3 habe ich die selben Probleme.
Ein Downgrade auf 1.0.0 ist nicht möglich.

![image](https://user-images.githubusercontent.com/52467622/132552320-ce0b9ce9-ea1a-49ab-8c98-4371384711a1.png)

**Comment by Rabenvater** [comment]
Gibt's hier schon Neuigkeiten zu vermelden?
Nach heutigem Upgrade auf 1.1.3 habe ich die selben Probleme.

Das PW kann nicht eingegeben werden und die NAS  meckert wegen
einem falschen PW. :-(

**Comment by Ricox1975** [comment]
ich bin wieder auf den ursprünglichen Adapter zurück. https://github.com/instalator/ioBroker.synology

**Comment by MeisterTR** [comment]
in der 2.0.1 ist das Passwortfeld ein normales Textfeld. Nur als workarround bis es im Admin gefixed ist.

**Comment by SmartHomer0** [comment]
Super - der Adapter lässt sich mit V2.01 wieder verwenden. Danke. 
Wenn es Dir vielleicht noch möglich wäre folgendes mal nachzusehen: 
In den früheren Adapter-Versionen (und noch unter DSM 6.x) wurde im ioBroker-Datenpunkt Volume/desc der Name des Volumes im Klartext ausgegeben:
![grafik](https://user-images.githubusercontent.com/90909896/133781505-4c897d93-3b84-4f28-94de-80def8f352a6.png)

Wäre dies auch jetzt wieder möglich?

Danke und Gruß

**Comment by TomasiDeveloping** [comment]
Ich laufe weiter auf Fehler seitens NAS.
Im Log erhalte ich immer das das Login gescheitert ist.
Jemand noch eine Idee ?
Passwort ist korrekt über die Weboberfläche kann ich mich einloggen.
Habe DSM 7

**Comment by TomasiDeveloping** [comment]
UPDATE:
Mit dem Update das Passwort als Klartext funktioniert der Adapter ohne Probleme mit 2FA und DSM 7
Besten Dank und hoffentlich wird auch das mit dem Passwort noch rasch gefixt

**Comment by maxpd1** [comment]
Nutze ebenfalls noch eine ds213j mit DSM 6 und hab den Synology Adapter unter Admin 5.2.1. installiert

**Comment by hungryhunter68** [comment]
Hallo,

ich hatte das gleiche Problem -> der Tipp mit "Umstellen auf das alte Admin Interface" hat bei mir funktioniert (siehe oben). Allerdings nur weil ich auch meinen Synology iobroker Account und die ioBroker IP auf der Synology wieder freigeschaltet habe (wird zumindest bei mir noch einigen Versuchen erst mal eine Weile gesperrt). 

Unter DSM7 geht das folgendermaßen:
Account: Control Panel -> Security -> Account -> Manage Protected Accounts -> genutzter Account aufgeführt?!??
IP Adresse: Control Panel -> Security -> Account -> Protection -> Allow/Block List -> Block List -> ioBroker IP aufgeführt?!?

Ich hoffe es hilft Euch weiter ....

Beste Grüße

**Comment by maxpd1** [comment]
Danke dir. Aber ich habe bei mir Kontoschutz und 2FA gänzlich deaktiviert, um in eine solche Falle nicht zu laufen. Dennoch wird der Adapter nicht grün.

**Comment by Apollon77** [comment]
@MeisterTR workaround for the issue commited to master!!
