### ISSUE TITLE
Add "NAS Server is on battery"

### ISSUE THREAD

**Issue by DcFamas** [iobroker-community-adapters/ioBroker.synology#116]
Hey there,
thanks for the adapter.
Is it possible to implement the information, that the NAS is working on battery as an object in ioBroker?

- Synology DS720+
- Adapter v. 1.1.3

![grafik](https://user-images.githubusercontent.com/35306967/152638388-674bc991-452c-44bc-8f18-08fde9d99094.png)

![grafik](https://user-images.githubusercontent.com/35306967/152638401-bf885d61-724e-4e00-83fb-414016b710f1.png)

Thanks for the upcoming answer.
Best regards
DcFamas

**Comment by Apollon77** [comment]
Question is how the API is for that and how to get this information...

**Comment by arteck** [comment]
i cant find any Info for this message in API Document

**Comment by DcFamas** [comment]
Hey guys,
thanks for your reply.
Since both of you released 2.1.4 and the opportunity to use ssh, maybe it would be possible to use the usv command via. ssh? 

![grafik](https://user-images.githubusercontent.com/35306967/163671101-3cce3309-918a-47c2-852f-6d906165fb83.png)

Best regards :)

**Comment by Apollon77** [comment]
Why yoyu then not simply install the nut adapter and allow NUT access to your NAS and then you have what you want including the full nut details

**Comment by DcFamas** [comment]
I did not know the existince of the adapter. That works for me, thank you! :)
