### ISSUE TITLE
Update js-controller from @3.3.22 to @4.0.4 >>>Object synology.0.SurveillanceStation.getSnapshotCamera is invalid: Default value has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by TheBrain26** [iobroker-community-adapters/ioBroker.synology#117]
<html>
<body>

synology.0 | 2022-02-06 16:22:36.612 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
synology.0 | 2022-02-06 16:22:36.611 | warn | Object synology.0.SurveillanceStation.getSnapshotCamera is invalid: Default value has to be type "string" but received type "number"

</body>
</html>

**Comment by tigger30926** [comment]
Hi,
i have the same message in the log.

**Comment by Apollon77** [comment]
Is this still an issue with the 2.0.1 from GitHub here?

**Comment by Apollon77** [comment]
Fixed on GitHub
