### ISSUE TITLE
2FA Code required / bug?

### ISSUE THREAD

**Issue by nils50122** [iobroker-community-adapters/ioBroker.synology#14]
hi,

i will fight with iobroker.synology adapter since my update from dsm6 to dsm7.

i try to delete the 1.0.0 stable and install these newest version which will include "dsm7 fix" in release notes.

I always get these error in debug mode "*** ERROR : src: *sendPolling syno[dsm][getPollingData] code: 403 message: 2-step verification code required"

the correct 2FA code is stored in instanz settings and will checked aprox 10 times?!

**Comment by MeisterTR** [comment]
please test with 1.1.3

**Comment by nils50122** [comment]
works now - many thanks!
