### ISSUE TITLE
Warnmeldungen für den Synology Adapter

### ISSUE THREAD

**Issue by weindler** [iobroker-community-adapters/ioBroker.synology#141]
Folgende Warnmeldungen erhalte ich
`<html><body>

synology.0 | 2022-03-09 17:35:30.464 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
synology.0 | 2022-03-09 17:35:30.460 | warn | Object  synology.0.SurveillanceStation.getSnapshotCamera is invalid: Default  value has to be type "string" but received type "number"

</body>
</html>`
Plattform
linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
1500 MHz
Modell
ARMv7 Processor rev 3 (v7l)
RAM
3.8 GB
System-Betriebszeit
00:09:30
Node.js
v14.19.0
time
1646844221693
timeOffset
-60
Anzahl der Adapter
400
NPM
6.14.16
js-controller
4.0.19

**Comment by Apollon77** [comment]
Is this still an issue with the 2.0.1 from GitHub here?

**Comment by Apollon77** [comment]
Please provide a debug log here based on Github 20.1 version

**Comment by Apollon77** [comment]
duplocate #117
