### ISSUE TITLE
Release New Stable Version 2.1.6 

### ISSUE THREAD

**Issue by tigger30926** [iobroker-community-adapters/ioBroker.synology#151]
Hi,
I wanted to ask when version 2.1.6 will be officially released. 
So that you can download it normally in ioBroker without the diversions via the GitHub installation. 
Since ioBroker currently warns against an installation via GitHub, an official release of version 2.1.6 would be really great. 

Should the current version 2.1.6 not be released for the time being, 
then official instructions on how to install the Apdater correctly via GitHub would be very helpful.  

Many thanks

**Comment by Apollon77** [comment]
The 2.1.6 is 6 days old and available in the Beta/Latest repository, so there is no need to install from GitHub ... The usual waiting time are roughly 14 days to see if there is feedback on issues.

So all is in it's normal process, or do I miss anything?

**Comment by tigger30926** [comment]
Unfortunately, version 1.1.3 is still offered in ioBroker and I would be very happy if version 2.1.0 (2022-03-25) or at least version 2.0.1 (2021-09-17) would be officially released.
Even if I activate the beta versions, I am not offered any more, hence this post. 

Many thanks

**Comment by Apollon77** [comment]
YOu can install the latest Beta using Custom install (enable expert mode) and "Install from npm" ... Update in Stablke will come soon
