### ISSUE TITLE
DSM shown as off, temperatur 0 degrees

### ISSUE THREAD

**Issue by bjornand1** [iobroker-community-adapters/ioBroker.synology#152]
I can install the plugin and set it up, but in HomeKit, the disk station always shows as off, despite being on, and the temperature readings are always zero degrees.

I can see no log entries for the plugin/device to help troubleshoot.

**Comment by Apollon77** [comment]
But bow you start mixing things ... what has The synology adapter and "homekit" to do with each other? You need to provide more information. So please check the adapter states first and show maybe screenshots of them ... and then tell what you talks about Homekit?

**Comment by bjornand1** [comment]
Truly sorry, I mixed this up with a different issue, a Homebridge plugin😵‍💫
