### ISSUE TITLE
restart der DS führt zu Anspringen des Kontoschutzes und damit Fehler im Adapter

### ISSUE THREAD

**Issue by dennis-BLN** [iobroker-community-adapters/ioBroker.synology#153]
Hallo zusammen,

ich habe mit meiner neuen DS und somit DSM 7 folgendes Problem:
wenn die Syno startet oder rebootet, toggelt der synology.0.info.connection dauerhaft zwischen true und false.

Bemerkbar macht sich das bei mir durch ein Überwachungsscript, was mich mit Zustandsinformationen versorgt.

Was passiert: der aktivierte Kontoschutz schlägt zu und sperrt den user.

Wenn ich die Sperre löse und den Adapter neu starte, ist alles gut, login klappt.

DS: DS1821+
DSM: 7.0.1-42218 update 3
JS-controller: 4.0.21
Node-Version: v12.22.12
OS: raspberry PI OS 64 bit (Linux raspi02 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
)
HW: raspberry 4 8 GB

adapter: 2.1.6 (aber auch zuvor mit der 1.x)
adapter config:
  2FA
  eigener user in der Gruppe admin auf der DS
  port 5001 und https true (auch bei 5000 und https false)
  API-Version 7.x.x

Wenn ihr mehr Infos braucht, meldet euch gerne.

Danke für Eure Unterstützung
Dennis

**Comment by Apollon77** [comment]
Bitte mal einen Debug log davon zeigen. Annahme wäre: Am Ende verliert der Adapter die verbindung und versucht es dann wieder ... vllt ist er dabei dann zu schnell ... aber würde es gern mal im Debug sehen - aber auch mit der Info was der Reboot begonnen war und wann er "fertig "war damit ich das zuordnen kann

**Comment by dennis-BLN** [comment]
[debug.log](https://github.com/iobroker-community-adapters/ioBroker.synology/files/8514811/debug.log)
gerne, timestamps habe ich unter der Bezeichnung "Zusatzinfo" eingefügt, geht um 18:23:20 los

**Comment by Apollon77** [comment]
bitte mal GitHub Version versuchen

**Comment by dennis-BLN** [comment]
Hi, der Fehler tritt mit der 2.1.6 ebenso auf.

**Comment by Apollon77** [comment]
Dann bitte neues Log

**Comment by dennis-BLN** [comment]
[synologyagent_test_v2.1.6.txt](https://github.com/iobroker-community-adapters/ioBroker.synology/files/8583327/synologyagent_test_v2.1.6.txt)

**Comment by Apollon77** [comment]
Bitte mit 2.1.7 nochmals versuchen und ggf neue slog liefern

**Comment by dennis-BLN** [comment]
Hi, 

habe zuerst das update DSM 7.0.1-42218 Update 4 installiert, damit trat der Fehler unter 2.1.6 nicht auf. Habe mehrere Neustarts der DS durchgeführt, zwischenzeitlich auch den iob samt server darunter neu gestartet. Fehler war nicht reproduzierbar.

Update auf 2.1.7 - erster DSM Neustart - Fehler tritt auf. Geändertes Verhalten: die Connection im Adapter bleibt auf false, das toggeln ist weg. 

Habe dann debug eingeschaltet, erster Neustart direkt nach shutdown (<60s) - erfolgreicher reconnect. Zweiter Versuch, DS mehrere Minuten aus gelassen: Fehler tritt auf. 

Logfile anbei.

Viele Grüße
Dennis
[synologyagent_test_v2.1.7.txt](https://github.com/iobroker-community-adapters/ioBroker.synology/files/8823880/synologyagent_test_v2.1.7.txt)

**Comment by Apollon77** [comment]
oookk, bitter mal GitHub Version versuchen, habe nochmal was gefixt undnreconnects auf 30s anstelle 10s gesetzt. Schau jetzt mal Bitte. Gern wieder log

**Comment by Apollon77** [comment]
@dennis-BLN any chance?

**Comment by dennis-BLN** [comment]
Hallo Ingo, 
hab es jetzt über mehrere Tage erfolgreich getestet, Fehler tritt aktuell nicht mehr auf, vielen Dank!

**Comment by dennis-BLN** [comment]
Hallo Ingo,
Ergänzung: mit dem Reboot nach dem aktuellen update auf DSM 7.1-42661 Update 2 trat der Fehler einmalig wieder auf. Danach testete ich mit reboot und shutdown - warten - und Neustart, Fehler tritt nicht auf.
Dennis

**Comment by Apollon77** [comment]
grrmmpfff ... wat machmer?? Bräuchte wenn nochmal Debug log wenns passiert .. das ist die krux

**Comment by OneCreek** [comment]
Ich hatte in der Vergangenheit immer massive Probleme. Seit der letzten Developer, die ja jetzt auch released ist, kann ich definiv damit arbeiten. Es tritt zwar das Problem immer noch manchmal auf bei Neustarts, aber nach 1-10 min ist die Verbindung dann stabil. 
Ich habe die 2FA am Laufen und bekomme wenn er den Status von Connected _true_ wieder kurzzeitig auf _false_ springt, auch eine Email Benachrichtigung von meiner Synology, dass ein _Authentification Failure_ aufgetreten ist, als sich mein User einloggen wollte.

**Comment by OneCreek** [comment]
Heute morgen bei Start gabs ein paar mehr Versuche... wieder mit _Authentification Failure_. nach den 5 Disconnects in den ersten 10 Minuten läuft es wieder stabil.
[2022-06-15a-k Synology.txt](https://github.com/iobroker-community-adapters/ioBroker.synology/files/8907455/2022-06-15a-k.Synology.txt)

**Comment by dennis-BLN** [comment]
Hallo Ingo,
hatte heute morgen Zeit für Testläufe, schon der erste verlief mit Fehler:
auf der syno ein Neustart per GUI angestoßen (08:22:43), Adapter schafft keinen reconnect - allerdings taucht der Client (iobroker) nicht in der Kontenschutzliste auf. Log anbei. Der Adapter meldet nun wieder abwechelnd Status "online" und "offline".
[20220621_0830_iobroker_synology.log](https://github.com/iobroker-community-adapters/ioBroker.synology/files/8946429/20220621_0830_iobroker_synology.log)

Viele Grüße
Dennis

**Comment by Apollon77** [comment]
Ooookkkk, dann noch ein Versuch. Im Log habe ich gesehen das er den player-Status abgefragt hat und hier " 4 Requests auf einmal gesendet" wurden ... damit sind es ggf schon zuviele Requests für die Erkennung. Das sollte jetzt nicht mehr passieren - wird nacheinander abgefragt (hoffe ich - nicht getestet!!).

Also bitte einerseits checken das Playerstatus noch passt und andererseits nochmal das thema.

Das könnte auch erklären warum es nur manchmal passiert ist weil halt er genau "Treffen" musste :-)

**Comment by dennis-BLN** [comment]
Hallo Ingo,
bin heute zum Update und Test gekommen. Nach dem Rollout war der adapter mit der syn verbunden, danach verlief es wie folgt:
15:20:11 shutdown DS
15:20:37 DS poweroff
15:22:21 DS WOL gesendet
15:25:10 DS up&running
seit 15:24 toggelte der adapter zwischen DS ist online und offline

Kontoschutz war nicht aktiv, dennoch keine Verbindung möglich
15:28 habe ich den adapter neu gestartet, Verbindung konnte hergestellt werden...

anbei das debug-LOG: [20220630_iobroker_synology.log](https://github.com/iobroker-community-adapters/ioBroker.synology/files/9022396/20220630_iobroker_synology.log)

Viele Grüße
Dennis

**Comment by Apollon77** [comment]
Also jetzt kapier ich gar nix mehr ... Das log sieht am Ende so aus wie ich es mit vorstelle...
* vor 15:22 EHOSTUNREACH
* 15:23:20 erste Anfrage geht direkt durch ... ohne andere Fehler vorher
* dann gehen 4 ANfragen durch ... beid er 5ten dann "404 message: Failed to authenticate 2-step verification code" :-(

Und dann iteriert es ... er wartet 30s und dann gehen wieder die ersten 4 durch und dann die fünfte wegen 2fa nicht

Nach dem Restart geht es leicht anders.

Vrsuch mal .... hab jetzt mal das verhalten nach Reconnect so umgebaut wie beim ersten start ... 

Also nochmal GitHub bitte :-) Und Danke!!

**Comment by dennis-BLN** [comment]
Hallo Ingo,
update ist installiert, shutdown DS, 09:52:37 WOL
danach gleiches Verhalten, log anbei
[20220701_1_iobroker_synology.log](https://github.com/iobroker-community-adapters/ioBroker.synology/files/9027268/20220701_1_iobroker_synology.log)

**Comment by Apollon77** [comment]
Hab noch eeeine Idee ... es gab einen quasi parallelen Request ... bitte nochmal checken

**Comment by dennis-BLN** [comment]
Hallo Ingo,
zwei Testläufe habe ich eben erfolgreich absolviert, das sieht gut aus!

**Comment by dennis-BLN** [comment]
Hi Ingo, 
der Dank geht an Dich, dass Du mein Problem nicht als Einzelfall ausgeblendet hast und dran geblieben bist!
Ja, hab noch mal getestet, aus meiner Sicht kannst Du die Version freigeben.

Vielen Dank und Grüße
Dennis

PS: ich habe es noch nie geschafft die DS per adapter herunterfahren zu lassen, wenn ich wieder etwas mehr Zeit habe, mach ich uns dazu ein Ticket auf :)

**Comment by Apollon77** [comment]
:-)

ABer zu shutdown hat doch Arteck was gemacht ... ssh aktivieren dann gerhts per ssh

**Comment by dennis-BLN** [comment]
ssh ... ist aktiviert, dennoch will er nicht... meine Vermutung ist, dass der verwendete user in der sudoers noch ein Recht auf init oder shutdown braucht:

2022-07-01 20:38:11.204  - debug: synology.0 (1062269) state synology.0.commands.shutdown changed: true (ack = false)
2022-07-01 20:38:11.304  - debug: synology.0 (1062269) *** ERROR : src: SSH Error: code: undefined message:
2022-07-01 20:38:14.925  - debug: synology.0 (1062269) *** ERROR : src: SSH Error: code: undefined message: Sorry, try again.
2022-07-01 20:38:14.926  - debug: synology.0 (1062269) *** ERROR : src: SSH Error: code: undefined message: sudo: no password was provided
2022-07-01 20:38:14.926  - debug: synology.0 (1062269) *** ERROR : src: SSH Error: code: undefined message: sudo: 1 incorrect password attempt
2022-07-01 20:38:14.928  - warn: synology.0 (1062269) System shutdown

**Comment by arteck** [comment]
nein da musst du nix eintragen.. der user muss nur admin rechte haben

**Comment by OneCreek** [comment]
> _holz klopf_ ... Sag wenn so ok das ich es releasen soll. Mega danke für deine geduld

bei mir läuft es jetzt auch stabil! Merci
