### ISSUE TITLE
can't get homemode enable to work

### ISSUE THREAD

**Issue by spcqike** [iobroker-community-adapters/ioBroker.synology#166]
Hello all,

maybe it's just me, but i can't figure out, how to send a command, so that homemode gets switched.

i tried several things, but it just will not work.
can someone provide an example of how to properly use it? 
my last approach looks like
```
sendTo("synology.0", "send", {
   "parameter1": {"method": "SurveillanceStation.HomeMode.status_on", "params": {"status_on":"true"}}
});
```

also the MessageBox example 
```
sendTo('synology.0', 'getSnapshot', {camId: 2}, (res) => {
    if(res) sendTo('telegram.0', {text: res, caption: 'caption for image'});
});
```
doesn't work for me. at least i'm not getting any message via telegram (where a simple "test" message works, so telegram-adapter works, too)

a simple getInfo gives me all information about my Diskstation, so i think the adapter works, but i just can't get it to send a command.
```
sendTo("synology.0", "send", {
   "parameter1": {"method": "getInfo", "params": {}}
});
```

thank you in advance

**Comment by Apollon77** [comment]
Does infos from https://github.com/iobroker-community-adapters/ioBroker.synology/issues/124 help somehow? Basically duplicate here, or?

**Comment by Apollon77** [comment]
Did you tried to ask in Forum if someone there has an idea?

**Comment by spcqike** [comment]
no, not yet, as this is the official repo :) i try to first check the docs to see how it should be done.
but i guess i need to ask in iobroker forum or somewhere, too :)

**Comment by mcm1957** [comment]
Reset stale-bot
