### ISSUE TITLE
Surveillance Station 9 Update gibt keine motionDetected Werte zurück

### ISSUE THREAD

**Issue by thstickel** [iobroker-community-adapters/ioBroker.synology#175]
Nach dem Update der Surveillance Station auf die Version 9.0.0-6860 wird das Objekt 
`synology.0.SurveillanceStation.cameras.Carport.motionDetected`   
nicht mehr gefüllt.

**Versionen:** 
 - Adapter version: v2.1.7
 - JS-Controller version: 4.0.23
 - Node version: v14.19.3
 - Operating system: Debian Buster

Der Adapter bleibt grün. Auch die Objekte werden augenscheinlich aktualisiert (Blinken kurz grün auf). Ändern aber die Werte nicht

<img width="1914" alt="Bildschirmfoto 2022-06-08 um 13 51 14" src="https://user-images.githubusercontent.com/25841553/172609699-d82f0348-c913-427b-ae70-5e18392d9670.png">
.

**Comment by Apollon77** [comment]
Please post e a log with changing loglevel of the instance to debug

**Comment by thstickel** [comment]
Nach Nachstart des Adapters werden die Werte wieder geschrieben. Entschuldige bitte - hätte ich vielleicht vorher drauf kommen können!
