### ISSUE TITLE
[Feature] Show status USB-USV

### ISSUE THREAD

**Issue by Thias66** [iobroker-community-adapters/ioBroker.synology#205]
Hello,

it's not really a Bub, but I would like to use the USB-USV status as a trigger for other automations. Would it be possible to add this info in your adapter?

Thanks for your work!!

**Comment by Apollon77** [comment]
You can use the nut adapter to get the USV Status. Just allow the ioBroker host/IP access in the settings for this. then done

**Comment by mcm1957** [comment]
I'll keep this isse as Feature request. But I would recommend to use Apollon77's suggestion.

Currently the synology adapter is a wrapper around kwent/syno module (https://github.com/kwent/syno) which seems to be become stale. Anyway tkwent's module seems to provide all information synologies rest interface provides.

So at the time of this writing I do not see a chance to implement USB Status support in the near future.

If anyone reading this has a link to a complete synology documentation of the rest interface, please provide this info. I did not yet find a complete rest documentation describing the official synology interface.

**Comment by CNC-Maniac** [comment]
> You can use the nut adapter to get the USV Status. Just allow the ioBroker host/IP access in the settings for this. then done

Yes, but you need an extra server for Nut.
I would also prefer to take the data directly from the Synology Adapter.

**Comment by Apollon77** [comment]
This is not true ... The NAS will be the NUT Server and an iobroker adapter will connect to it ... no extra server needed. Check the Synology settings and you need to allow the IP access then for the iobroker host

**Comment by CNC-Maniac** [comment]
Unfortunately, only newer synos offer this option. I have an old DS212. Since no UPS server can be activated.

**Comment by Apollon77** [comment]
Ok ... I started with DS213 and it was there ...

**Comment by CNC-Maniac** [comment]
Funny now I can activate the server?!
I also found the data on the net: user=monuser, password=none, name of UPS=ups
Everything works now, thanks for the tip

**Comment by Apollon77** [comment]
A check in the nut adapter readme would have also helped :-) https://github.com/Apollon77/ioBroker.nut#ups_name
