### ISSUE TITLE
wrong repository link in iobroker plugins list

### ISSUE THREAD

**Issue by Z18Aplha** [iobroker-community-adapters/ioBroker.synology#21]
**Describe the bug**  
Installation from adapter's list doesn't work due to an GET error of npm.

**To Reproduce**  
1. Go to the adapter page in ioBroker
2. Click on "+" of Synology NAS
3. Click "more" while running the installation
4. See error: ```npm ERR! 404 Not Found - GET https://github.com/homeinstalator/syno/tarball/master/```

**Expected behavior**  
A flawless installation and a pop up of the settings of the adapter.

**Additional context**  
I already tried to open the repository by myself. It resulted also in an error 404. I would assume, the repository link is just very old and needs to be updated.

**Comment by Apollon77** [comment]
WHich version you tried to ijstall? Please try the latest npm version

**Comment by mrjeschke** [comment]
Gleiches Problem.

`pi@iobroker:~ $ npm install iobroker.synology@1.0.0 --loglevel error --prefix "/opt/iobroker"
npm ERR! code E404
npm ERR! 404 Not Found - GET https://codeload.github.com/homeinstalator/syno/legacy.tar.gz/master
npm ERR! 404
npm ERR! 404  'syno@https://github.com/homeinstalator/syno/tarball/master/' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'iobroker.synology'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-09-04T19_12_19_859Z-debug.log


pi@iobroker:~ $ npm install iobroker.synology@1.1.3 --loglevel error --prefix "/opt/iobroker"
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.synology@1.1.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-09-04T19_13_00_611Z-debug.log


pi@iobroker:~ $ npm show iobroker.synology versions
[
  '0.0.2',  '0.0.3',  '0.0.4',
  '0.1.0',  '0.1.1',  '0.1.2',
  '0.1.3',  '0.1.4',  '0.1.5',
  '0.1.6',  '0.1.7',  '0.1.8',
  '0.1.9',  '0.1.10', '0.1.11',
  '0.1.12', '0.1.14', '0.1.15',
  '0.1.16', '0.1.17', '0.1.18',
  '0.1.19', '0.1.20', '1.0.0'
]
`
Sollte der Versuch etwa so Aussehen?

**Comment by Apollon77** [comment]
Please install from GitHub for now, we release soon a new version

**Comment by Z18Aplha** [comment]
> WHich version you tried to ijstall? Please try the latest npm version

It should have been 1.0.0.

> Please install from GitHub for now, we release soon a new version

Thank you for the answer. When i use github to install the adapter, it does not appear in my adapters list. Only the folder synology.0 is created. Nothing else. The adapters page shows the correct version number 1.1.3.

**Comment by Apollon77** [comment]
Yes after GitHub install you need to manually create an instace. Use the "+" button on Adapter
