### ISSUE TITLE
Kann nach dem Update das PW nicht mehr eingeben 

### ISSUE THREAD

**Issue by Rabenvater** [iobroker-community-adapters/ioBroker.synology#25]
Gibt's hier schon Neuigkeiten zu vermelden?
Nach heutigem Upgrade auf 1.1.3 habe ich die selben Probleme.
Ein Downgrade auf 1.0.0 ist nicht möglich.

Ich kann das PW nicht mehr eingeben und meine NAS meckert
wegen einem falschen PW. 

Habt ihr ne Idee?

**Comment by Apollon77** [comment]
duplicate #11
