### ISSUE TITLE
motionDetected doesn't change when recording mode is continuous

### ISSUE THREAD

**Issue by ChrisVonFrosta** [iobroker-community-adapters/ioBroker.synology#285]
Hi,
don't know if this is a bug or not.
If the recording mode is continuous, i can still see the movement marks in the timeline.
But the object motionDetected in ioBroker is only effected when recording mode is on motion.
I would like to keep recording on continuous and do stuff when movement is detected.

thx

**Comment by DemigodCode** [comment]
Hey,

got it working. The trick is to select the motion detection as standard schedule.
The continuous mode should be set as double recording.

Then it updates the motionDetect to true, but you have to set it back to false by yourself.
I've chosen 15 MInutes to set it back to false.

**Comment by ChrisVonFrosta** [comment]
Thank you!
