### ISSUE TITLE
commands - reboot/shutdown - not work

### ISSUE THREAD

**Issue by Lyxon1337** [iobroker-community-adapters/ioBroker.synology#38]
**Describe the bug**  
reboot/shutdown - not work

**To Reproduce**  
1. Go to 'object' -> 'synology' -> 'coommands'
2. Click on 'shutdown' or 'reboot'
3. Set anthing u want (tested boolean, number, string, json)
4. See ... nothing

**Expected behavior**  
obvisly shutdown or reboot... :D

**Screenshots & Logfiles**  
Logfiles empty.
Only 'not ACK' make entry
![grafik](https://user-images.githubusercontent.com/91346264/134735654-347a6ae8-f4bc-4cf6-b492-2dc5b26a6253.png)
![grafik](https://user-images.githubusercontent.com/91346264/134735711-9286101a-283f-4b45-bc6d-05097981e2ef.png)
aaaaand... still online... am I doing something wrong?

**Versions:**  
 - Adapter version: Testet with 1.1.3 and 2.0.1
 - JS-Controller version: 3.3.18
 - Node version: Tested with 12.22.5 and 12.22.6
 - Operating system: Linux in Docker on Synology

**Additional context**  
Tested on: DS620slim, DS718+, DS418, DS1817+
all are DSM 7.0-41890

**Comment by arteck** [comment]
here also but with DSM 6.x

**Comment by MC-1984** [comment]
Same here on current DSM 7

**Comment by lwalpurgis** [comment]
Same here also on DSM 7. It would be really nice, if this functionaility works again!

**Comment by Pedder007** [comment]
Same here:
DS218play
DSM 6.2.4-25556 Update 2
Instance API Version: 6.2.3

**Comment by jakob-huber** [comment]
Yes, same here
DS920+
DSM 7.0.1-42218

**Comment by Kuddel071089** [comment]
Same here
DS213j
DSM 7.0-41890

**Comment by tigger30926** [comment]
Hi,
I already reported the problem here on 10/14/2021. What I have noticed in the last few days is that the problem somehow relates to shutting down. Starting or waking up the disk stations works from time to time. Unfortunately, you can no longer rely on it. I wonder what else we can do to help the developer find the problem or solve it for us?

DS216J
DSM 6.2.4-25556 Update 2
API: 6.2.3

**Comment by tigger30926** [comment]
Hello, 
what can we do to support the programmer here? 
Because we now need a suitable change so that the plugin works properly again. 
I would like to continue using the plugin, therefore this really serious call.

**Comment by arteck** [comment]
> Hi, I already reported the problem here on 10/14/2021. What I have noticed in the last few days is that the problem somehow relates to shutting down. Starting or waking up the disk stations works from time to time. Unfortunately, you can no longer rely on it. I wonder what else we can do to help the developer find the problem or solve it for us?
> 
> DS216J DSM 6.2.4-25556 Update 2 API: 6.2.3

the adapter is a community project.. and that is not only one.. we have other problems ..SRY

**Comment by tigger30926** [comment]
> > Hi, I already reported the problem here on 10/14/2021. What I have noticed in the last few days is that the problem somehow relates to shutting down. Starting or waking up the disk stations works from time to time. Unfortunately, you can no longer rely on it. I wonder what else we can do to help the developer find the problem or solve it for us?
> > DS216J DSM 6.2.4-25556 Update 2 API: 6.2.3
> 
> the adapter is a community project.. and that is not only one.. we have other problems ..SRY

I understand that, but there is nothing wrong with looking for a solution together. If there is a problem, I would like to help solve it. I think it's the same for many people here and if you could tell us how we can support you in finding a solution, maybe other problems would be solved more quickly.

**Comment by tigger30926** [comment]
Hi,
I have just seen that all these versions are available online.

Changelog
2.0.1 (2021-09-17)
(MasterTR) Workaround JSON config Password
2.0.0
(instalator) DSM7 support

But in my IOBroker these are not offered for updating. 
Is there any way I can run this manually? 
I tried to find this via the beta search, but found nothing here either.
There is also no new Apdater with V2.0.

Many thanks

**Comment by bluefish007** [comment]
@tigger30926 
You can install directly from github repository: enable the expert mode, click on "cat", click on "from github" and select the desired iobroker adapter in the list ... :)

**Comment by tigger30926** [comment]
> @tigger30926 You can install directly from github repository: enable the expert mode, click on "cat", click on "from github" and select the desired iobroker adapter in the list ... :)

Ok, thank you, I have found it. But I'm not quite sure whether I could break something this way. The warning texts are quite clear. When will V.2.0 be distributed via the normal route? Because currently this adapter no longer works at all.

**Comment by Apollon77** [comment]
Is this still an issue with the 2.0.1 from GitHub here?

**Comment by MC-1984** [comment]
Unfortunately, it is still not working with version 2.0.1

**Comment by tigger30926** [comment]
Does anyone know what is actually causing the problem? Until a few weeks ago, the DiskStation was started from time to time, but it never reacted to the shutdown. I would be really happy if you could solve the problem, even if other things are perhaps more important. We have been waiting for help for such a long time now. 

I would still be interested if I install the latest Github version via the Expert mode, can I simply install this as a beginner without any worries? I would like to support you as much as possible and give you feedback on what works and what does not.

**Comment by Kuddel071089** [comment]
At the Moment, i'm using an javascript as workaround for shutdown. mfa is not activated

`on(
	{id: "0_userdata.0.shutdown.shutdown_synology", change: 'any'}, function (obj) {
		var SSH = require('simple-ssh');
		var ssh = new SSH({
			host: '192.168.4.12',
			port: 22,
			user: 'USER_XYZ',
			pass: 'PASSWORD_XYZ!'
		});
		ssh.exec('echo "PASSWORD_XYZ"|sudo -S shutdown -h now').start();   
		}
);

`

**Comment by Apollon77** [comment]
Cqan someone please provide a debug log fro this instan ce (so change loglevel to debug) and post log from triggering the reboot/shutdown state (ack=false is required!)

**Comment by tigger30926** [comment]
> Cqan someone please provide a debug log fro this instan ce (so change loglevel to debug) and post log from triggering the reboot/shutdown state (ack=false is required!)

Hi, so I would love to provide you with the data, but I haven't done that yet. I have set the logen to debug level, but what do you mean by "ack"? I can't find it at the moment to set it. This is what is currently displayed in the log:

2022-03-25 06:28:08.138 - info: javascript.0 (127) script.js.Scripte.Fertige.Diskstation-Energiesparen: WOL Paket Diskstation-1 gesendet
--
2022-03-25 06:28:08.148 - info: javascript.0 (127) script.js.Scripte.Fertige.Diskstation-Energiesparen: WOL Paket Diskstation-5 gesendet
2022-03-25 06:28:38.141 - info: javascript.0 (127) script.js.Scripte.Fertige.Diskstation-Energiesparen: WOL Paket Diskstation-7 gesendet
2022-03-25 06:30:47.017 - info: synology.4 (368) Connecting to Synology 192.168.50.51.:5000
2022-03-25 06:31:02.641 - info: synology.0 (29821) Connecting to Synology 192.168.50.51:5000
2022-03-25 06:31:18.566 - info: synology.6 (398) Connecting to Synology 192.168.50.57:5000
2022-03-25 07:17:05.581 - info: host.f1f45637fe88 stopInstance system.adapter.synology.0 (force=false, process=true)
2022-03-25 07:17:05.585 - info: synology.0 (29821) Got terminate signal TERMINATE_YOURSELF
2022-03-25 07:17:05.585 - info: synology.0 (29821) terminating
2022-03-25 07:17:05.585 - info: synology.0 (29821) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-03-25 07:17:05.587 - info: host.f1f45637fe88 stopInstance system.adapter.synology.0 send kill signal
2022-03-25 07:17:06.127 - info: host.f1f45637fe88 instance system.adapter.synology.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-03-25 07:17:08.671 - info: host.f1f45637fe88 instance system.adapter.synology.0 started with pid 19147
2022-03-25 07:17:10.213 - warn: synology.0 (19147) Object synology.0.SurveillanceStation.getSnapshotCamera is invalid: Default value has to be type "string" but received type "number"
2022-03-25 07:17:10.214 - warn: synology.0 (19147) This object will not be created in future versions. Please report this to the developer.
2022-03-25 07:17:10.275 - info: synology.0 (19147) starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.synology, node: v14.19.0, js-controller: 4.0.21
2022-03-25 07:17:10.305 - info: synology.0 (19147) Connecting to Synology 192.168.50.51:5000

**Comment by Apollon77** [comment]
1.) Please install GitHub version
2.) Debug: in Admin: Instances - enable expertmode - expand instance, set loglevel to debug ... then adapter restarts ... then you will see debug logging
3.) When you set a state you can choose the ack flag (German: bestätigt) ... This needs to be "false" in order to control anything

**Comment by arteck** [comment]
check new version 2.1.3

**Comment by Apollon77** [comment]
Fixed in 2.1.4 ... you need to provide your SSHport in the settings (will try port 22 by default!)
