### ISSUE TITLE
object/data point "volume description" empty

### ISSUE THREAD

**Issue by SmartHomer0** [iobroker-community-adapters/ioBroker.synology#39]
In earlier Adapter-versions (and under DSM 6.x) the name of the volume was shown as a text string under ioBroker data point Volume/desc:

![grafik](https://user-images.githubusercontent.com/90909896/134916690-9f65d7dc-b98e-4ec6-9e62-cdc18c6b5efa.png)

Is it possible to get this function back?

Thanks

**Comment by SmartHomer0** [comment]
Seems that my issue isn't interresting to others, so it won't be worked at a solution. Thanks anyway

**Comment by Apollon77** [comment]
who said that? The stale bot just verifies if an issue is still valid and relevant ... and yes till now no developer had time ... do not mean that it won't be done somewhen.

**Comment by SmartHomer0** [comment]
Great - thanks a lot for your answer/comment

**Comment by Apollon77** [comment]
Is this still an issue with the 2.0.1 from GitHub here?

**Comment by SmartHomer0** [comment]
Thank you for being interrested.
I checked again - it is still the same (even after having deleted the object tree and restarted the adapter):

<img width="815" alt="image" src="https://user-images.githubusercontent.com/90909896/159666948-f0529a1d-72ac-4b81-90db-c327fbfd0199.png">

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/90909896/159666831-d2906f0e-320a-48ba-b370-3c8a654edaed.png">

**Comment by Apollon77** [comment]
Pleasse enable debug logging for the instance and then check log for a line containing "InfoSystem - Response ..." and post this line (or full log) please

**Comment by SmartHomer0** [comment]
@Apollon77  
Here the requested information, I hope it is helpful.
It's a Synology DS918+ equipped with four HDD and five active volumes

`<html><body>


synology.0 | 30268 | 2022-03-25 09:24:21.440 | debug | -----------------------------------------------------------------------------------------------------
-- | -- | -- | -- | --
synology.0 | 30268 | 2022-03-25 09:24:21.440 | debug | InfoSystem  - Response:  {"hdd_info":[{"capacity":"4000787030016","diskPath":"/dev/sda","diskType":"SATA","diskno":"Drive   1","ebox_order":0,"model":"WD40EFRX-68N32N0","order":1,"overview_status":"normal","pciSlot":-1,"portType":"normal","status":"normal","summary_status_category":"space","summary_status_key":"normal","temp":30,"testing_progress":"","testing_type":"idle","volume":"reuse_1"},{"capacity":"4000787030016","diskPath":"/dev/sdb","diskType":"SATA","diskno":"Drive   2","ebox_order":0,"model":"WD40EFRX-68N32N0","order":2,"overview_status":"normal","pciSlot":-1,"portType":"normal","status":"normal","summary_status_category":"space","summary_status_key":"normal","temp":31,"testing_progress":"","testing_type":"idle","volume":"reuse_1"},{"capacity":"4000787030016","diskPath":"/dev/sdc","diskType":"SATA","diskno":"Drive   3","ebox_order":0,"model":"WD40EFRX-68N32N0","order":3,"overview_status":"normal","pciSlot":-1,"portType":"normal","status":"normal","summary_status_category":"space","summary_status_key":"normal","temp":31,"testing_progress":"","testing_type":"idle","volume":"reuse_1"},{"capacity":"4000787030016","diskPath":"/dev/sdd","diskType":"SATA","diskno":"Drive   4","ebox_order":0,"model":"WD40EFRX-68N32N0","order":4,"overview_status":"normal","pciSlot":-1,"portType":"normal","status":"normal","summary_status_category":"space","summary_status_key":"normal","temp":31,"testing_progress":"","testing_type":"idle","volume":"reuse_1"}],"vol_info":[{"desc":"","inode_free":"134127222","inode_total":"134217728","name":"volume_1","status":"normal","total_size":"2164374028288","used_size":"214962262016","vol_desc":"Daten   Allgemein","volume":"volume_1"},{"desc":"","inode_free":"66799211","inode_total":"67108864","name":"volume_3","status":"attention","total_size":"1082120392704","used_size":"916301991936","vol_desc":"Technik","volume":"volume_3"},{"desc":"","inode_free":"16224947","inode_total":"16777216","name":"volume_4","status":"normal","total_size":"270429917184","used_size":"58500087808","vol_desc":"Synology-Pakete   Installation","volume":"volume_4"},{"desc":"","inode_free":"67101965","inode_total":"67108864","name":"volume_2","status":"normal","total_size":"1082120392704","used_size":"700036235264","vol_desc":"Image","volume":"volume_2"},{"desc":"","inode_free":"0","inode_total":"0","name":"volume_5","status":"normal","total_size":"263882792960","used_size":"36084944896","vol_desc":"VirtualMachines","volume":"volume_5"}]}
synology.0 | 30268 | 2022-03-25 09:24:21.439 | debug | * The response is received, parse:
synology.0 | 30268 | 2022-03-25 09:24:20.992 | debug | * Get info from (fastPoll) api: DSM method: infoSystem params: {"type":"storage","version":1}
synology.0 | 30268 | 2022-03-25 09:24:20.991 | debug | *  sendPolling. namePolling = fastPoll \| iteration = 3 \| typeof poll =  object \| poll =  {"api":"dsm","method":"infoSystem","params":{"type":"storage","version":1}}


</body>
</html>`

**Comment by Apollon77** [comment]
Fixed on GitHub

**Comment by SmartHomer0** [comment]
With v2.1.0 on GitHub the object/data point "volume description" works fine again, Thanks to @Apollon77 for your work
