### ISSUE TITLE
Anmeldung schlägt fehl DSM 7

### ISSUE THREAD

**Issue by totocotonio** [iobroker-community-adapters/ioBroker.synology#48]
Hi,
ich habe den Adapter inst.und versucht ihn online zu bringen.

Keine Chance ob mit oder ohne 2fa .

Extra ein Konto bei der DSM angelegt, der Adapter wird nicht grün.
Wo finde ich die API Version was muss ich einstellen.

Wenn ich das Passwort eingebe kann ich nicht sehen was ich eingebe, das Feld verschwindet.

Ich bitte um Hilfe.

**Comment by bjoernszw** [comment]
HAllo,

ich hab die Version 2.01. aber mit und ohne 2FA bekomme ich keine Verbindung.
starting. Version 2.0.1 in C:/SMARTHOME/SmartHome/node_modules/iobroker.synology, node: v14.17.6, js-controller: 3.3.15
Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

Was könnte das Problem sein?

Viele Grüße

**Comment by Lyxon1337** [comment]
Hallo bjoernszw,

wenn alle andere settings (account mit admin rechte // firewall synology // http oder https settings // ... ) auf der synology richtig eingestellt sind und passend alles im Adapter eingestellt ist... Sollte es funktionieren...

Wie sieht deine umgebung aus? benutzt du zB VLAN?
mehr input :)

Bei den Settings zB im Adapter passt bei mir alles Supi (wenn die Syno passend eingestellt ist):
![grafik](https://user-images.githubusercontent.com/91346264/142773154-d26445c2-d33d-45db-b042-d759fbdb1547.png)


Grüße,
Lyxon

**Comment by bjoernszw** [comment]
Hallo Lyxon,

hab mir auch nen extra Admin eingerichtet und auch nochmal ohne 2FA.
meine Settings sehen so aus:
![image](https://user-images.githubusercontent.com/84512347/142812538-3cae3ea0-1bd7-4086-a679-65ee3f75a33b.png)

Kein VLAN, Firewall an der NAS ist abgeschaltet.

Im Log steht nur:
![image](https://user-images.githubusercontent.com/84512347/142811463-a9166018-621b-4f20-9f72-c498b510a1ca.png)

**Comment by Lyxon1337** [comment]
Hallo bjoernszw,

könnte mehrere Gründe haben...
habe schonmal vergessen mich selbst mit dem iobroker-admin account bei der syno anzumelden.
Da kam auch irgendeine fehlermeldung... Beim ersten anmelden muss man ja das Passwort ändern.

Was mir auch mal passiert ist.,. PW im Adapter vertippt.. klein L und groß i ist eine böse falle...
Das Ergebnis war das durch die Sicherheitseinstellung von der Syno die IP geblockt wurde...
Nachschauen in der Syno bei der Blockierungsliste (unter Sicherheit -> Schutz) und dann halt korrigieren

Ansonsten hab ich ber der Syno folgende Settings (ob die benötigt werden müsstest du try & error testen):
Syno -> Systemsteuerung -> Netzwerk -> Konnektivität -> Kreuz bei HTTP/2
Syno -> Systemsteuerung -> Sicherheit -> Erweitert -> Kreuz bei HTTP-Komprimierung
Syno -> Systemsteuerung -> Sicherheit -> Erweitert -> Punkt bei TLS "Moderne Kompatibilität"
Syno -> Systemsteuerung -> Anmeldeportal -> DSM -> Kreuz bei HTTP-Verbindung für... bla bla
Und natürlich ein aktuelles Zertifikat versteht sich... Hab das olle standardzertifikat

Wenn das alles nicht funktioniert... könnte es auch probleme mit node geben... da kann ich kaum helfen oder fehler suchen
Ich hab aktuell 12.22.6 installiert und du hast ja 14.17.6... wie du schreibst
Ebenso hab ich js-controller 3.3.18 und du hast 3.3.15...
Ob da der Hase begraben sein könnte... Muss jemand anders weiterhelfen

Hoffentlich klappt es :)

Grüße,
Lyxon

**Comment by bjoernszw** [comment]
Hi Lyxon,

das hier war das Problem:
Nachschauen in der Syno bei der Blockierungsliste (unter Sicherheit -> Schutz) und dann halt korrigieren

So richtig bin ich dahintergekommen als ich den Debug Level mal alles darstellen lassen hab.

Danke! Gruß
