### ISSUE TITLE
Wrong type since JS-Controller 3.3

### ISSUE THREAD

**Issue by metaxa1** [iobroker-community-adapters/ioBroker.synology#6]
v1.0.0
<html>
<body>

synology.0 | 2021-08-07 14:31:22.994 | info | (19060) State value to set for "synology.0.DiskStationManager.vol_info.volume_1.used_size" has to be type "number" but received type "string"
-- | -- | -- | --

</body>
</html>

<html>
<body>
<pre class="markdown-highlight" style="box-sizing: border-box; overflow: auto; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: 13px; display: block; padding: 9.5px; margin: 1rem 0px 10px; line-height: 1.42857; word-break: break-all; overflow-wrap: break-word; color: rgb(51, 51, 51); background-color: rgb(255, 255, 255); border: none; border-radius: 0px; max-height: 350px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="hljs sql" data-lines="1" style="box-sizing: border-box; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: inherit; padding: 0.5em; color: rgb(230, 225, 220); background: rgb(35, 35, 35); border-radius: 0px; white-space: pre; display: inline-block; overflow-x: auto; overflow-wrap: normal; min-width: 100%;">

  | synology.0	2021-08-05 21:47:48.906	info	(19060) State value to set for "synology.0.DiskStationManager.info.uptime" has to be type "string" but received type "number"
-- | --

</code></pre>
</body>
</html>

Edit
Nach heutigem Neustart des Adapters sind leider noch etliche Fehlermeldungen dazugekommen
`
<html>
<body>

  |   |   |  
-- | -- | -- | --
synology.0 | 2021-08-08 12:00:01.275 | info | (18123) State value to set for "synology.0.DiskStationManager.vol_info.volume_1.used" has to be type "number" but received type "string"
synology.0 | 2021-08-08 12:00:01.273 | info | (18123) State value to set for "synology.0.DiskStationManager.vol_info.volume_1.total_size" has to be type "number" but received type "string"
synology.0 | 2021-08-08 12:00:01.270 | info | (18123) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_4.capacity" has to be type "number" but received type "string"
synology.0 | 2021-08-08 12:00:01.267 | info | (18123) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_4.ebox_order" has to be type "string" but received type "number"
synology.0 | 2021-08-08 12:00:01.240 | info | (18123) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_3.capacity" has to be type "number" but received type "string"
synology.0 | 2021-08-08 12:00:01.234 | info | (18123) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_3.ebox_order" has to be type "string" but received type "number"
synology.0 | 2021-08-08 12:00:01.220 | info | (18123) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_2.capacity" has to be type "number" but received type "string"
synology.0 | 2021-08-08 12:00:01.213 | info | (18123) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_2.ebox_order" has to be type "string" but received type "number"
synology.0 | 2021-08-08 12:00:01.023 | info | (18123) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_1.capacity" has to be type "number" but received type "string"
synology.0 | 2021-08-08 12:00:01.013 | info | (18123) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_1.ebox_order" has to be type "string" but received type "number"
synology.0 | 2021-08-08 12:00:01.008 | info | (18123) State value to set for "synology.0.DiskStationManager.info.upgrade_ready" has to be type "string" but received type "boolean"
synology.0 | 2021-08-08 12:00:01.005 | info | (18123) State value to set for "synology.0.DiskStationManager.info.is_system_crashed" has to be type "string" but received type "boolean"
synology.0 | 2021-08-08 12:00:01.000 | info | (18123) State value to set for "synology.0.DiskStationManager.info.memory_size" has to be type "string" but received type "number"
synology.0 | 2021-08-08 11:59:46.609 | info | (18123) State value to set for "synology.0.FileStation.info.uid" has to be type "string" but received type "number"
synology.0 | 2021-08-08 11:59:46.604 | info | (18123) State value to set for "synology.0.FileStation.info.support_virtual.enable_remote_mount" has to be type "string" but received type "boolean"
synology.0 | 2021-08-08 11:59:46.603 | info | (18123) State value to set for "synology.0.FileStation.info.support_virtual.enable_iso_mount" has to be type "string" but received type "boolean"
synology.0 | 2021-08-08 11:59:46.602 | info | (18123) State value to set for "synology.0.FileStation.info.support_vfs" has to be type "string" but received type "boolean"
synology.0 | 2021-08-08 11:59:46.601 | info | (18123) State value to set for "synology.0.FileStation.info.support_sharing" has to be type "string" but received type "boolean"
synology.0 | 2021-08-08 11:59:46.600 | info | (18123) State value to set for "synology.0.FileStation.info.support_file_request" has to be type "string" but received type "boolean"
synology.0 | 2021-08-08 11:59:46.599 | info | (18123) State value to set for "synology.0.FileStation.info.items.2" has to be type "string" but received type "object"
synology.0 | 2021-08-08 11:59:46.598 | info | (18123) State value to set for "synology.0.FileStation.info.items.1" has to be type "string" but received type "object"
synology.0 | 2021-08-08 11:59:46.596 | info | (18123) State value to set for "synology.0.FileStation.info.items.0" has to be type "string" but received type "object"
synology.0 | 2021-08-08 11:59:46.596 | info | (18123) State value to set for "synology.0.FileStation.info.is_manager" has to be type "string" but received type "boolean"
synology.0 | 2021-08-08 11:59:46.594 | info | (18123) State value to set for "synology.0.FileStation.info.enable_list_usergrp" has to be type "string" but received type "boolean"
synology.0 | 2021-08-08 11:59:46.591 | info | (18123) State value to set for "synology.0.DiskStationManager.info.temperature_warn" has to be type "string" but received type "boolean"
synology.0 | 2021-08-08 11:59:40.909 | info | (18123) Connecting to Synology 192.168.0.98:5000
synology.0 | 2021-08-08 11:59:40.858 | info | (18123) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.synology, node: v12.22.2, js-controller: 3.3.15

</body>
</html>`

**Comment by guergen1** [comment]
hier auch

**Comment by MeisterTR** [comment]
fixed in 1.1.1

**Comment by metaxa1** [comment]
I'm sorry, but after updating to v1.1.1, the same log entries sometimes appear again.
I stopped the adapter and deleted all data points on the objects. The v1.1.1. installed via GitHub Link over it and restarted the adapter 2x. What did 1 wrong?

`
<html>
<body>


synology.0 | 2021-08-09 11:48:00.704 | info | (30961) State value to set for "synology.0.DiskStationManager.vol_info.volume_1.used_size" has to be type "number" but received type "string"
-- | -- | -- | --
synology.0 | 2021-08-09 11:48:00.654 | info | (30961) State value to set for "synology.0.DiskStationManager.vol_info.volume_1.total_size" has to be type "number" but received type "string"
synology.0 | 2021-08-09 11:48:00.653 | info | (30961) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_4.capacity" has to be type "number" but received type "string"
synology.0 | 2021-08-09 11:48:00.648 | info | (30961) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_4.ebox_order" has to be type "string" but received type "number"
synology.0 | 2021-08-09 11:48:00.646 | info | (30961) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_3.capacity" has to be type "number" but received type "string"
synology.0 | 2021-08-09 11:48:00.645 | info | (30961) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_3.ebox_order" has to be type "string" but received type "number"
synology.0 | 2021-08-09 11:48:00.640 | info | (30961) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_2.capacity" has to be type "number" but received type "string"
synology.0 | 2021-08-09 11:48:00.639 | info | (30961) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_2.ebox_order" has to be type "string" but received type "number"
synology.0 | 2021-08-09 11:48:00.631 | info | (30961) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_1.capacity" has to be type "number" but received type "string"
synology.0 | 2021-08-09 11:48:00.630 | info | (30961) State value to set for "synology.0.DiskStationManager.hdd_info.sata_drive_1.ebox_order" has to be type "string" but received type "number"
synology.0 | 2021-08-09 11:48:00.624 | info | (30961) State value to set for "synology.0.DiskStationManager.info.upgrade_ready" has to be type "string" but received type "boolean"
synology.0 | 2021-08-09 11:48:00.623 | info | (30961) State value to set for "synology.0.DiskStationManager.info.is_system_crashed" has to be type "string" but received type "boolean"
synology.0 | 2021-08-09 11:48:00.621 | info | (30961) State value to set for "synology.0.DiskStationManager.info.memory_size" has to be type "string" but received type "number"
synology.0 | 2021-08-09 11:47:42.968 | info | (30961) State value to set for "synology.0.FileStation.info.uid" has to be type "string" but received type "number"
synology.0 | 2021-08-09 11:47:42.966 | info | (30961) State value to set for "synology.0.FileStation.info.support_virtual.enable_remote_mount" has to be type "string" but received type "boolean"
synology.0 | 2021-08-09 11:47:42.964 | info | (30961) State value to set for "synology.0.FileStation.info.support_virtual.enable_iso_mount" has to be type "string" but received type "boolean"
synology.0 | 2021-08-09 11:47:42.963 | info | (30961) State value to set for "synology.0.FileStation.info.support_vfs" has to be type "string" but received type "boolean"
synology.0 | 2021-08-09 11:47:42.962 | info | (30961) State value to set for "synology.0.FileStation.info.support_sharing" has to be type "string" but received type "boolean"
synology.0 | 2021-08-09 11:47:42.961 | info | (30961) State value to set for "synology.0.FileStation.info.support_file_request" has to be type "string" but received type "boolean"
synology.0 | 2021-08-09 11:47:42.959 | info | (30961) State value to set for "synology.0.FileStation.info.items.2" has to be type "string" but received type "object"
synology.0 | 2021-08-09 11:47:42.958 | info | (30961) State value to set for "synology.0.FileStation.info.items.1" has to be type "string" but received type "object"
synology.0 | 2021-08-09 11:47:42.925 | info | (30961) State value to set for "synology.0.FileStation.info.items.0" has to be type "string" but received type "object"
synology.0 | 2021-08-09 11:47:42.918 | info | (30961) State value to set for "synology.0.FileStation.info.is_manager" has to be type "string" but received type "boolean"
synology.0 | 2021-08-09 11:47:42.916 | info | (30961) State value to set for "synology.0.FileStation.info.enable_list_usergrp" has to be type "string" but received type "boolean"
synology.0 | 2021-08-09 11:47:42.914 | info | (30961) State value to set for "synology.0.DiskStationManager.info.temperature_warn" has to be type "string" but received type "boolean"
synology.0 | 2021-08-09 11:47:41.584 | info | (30961) DSM 6
synology.0 | 2021-08-09 11:47:36.166 | info | (30961) Connecting to Synology 192.168.0.98:5000
synology.0 | 2021-08-09 11:47:36.060 | info | (30961) starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.synology, node: v12.22.2, js-controller: 3.3.15
synology.0 | 2021-08-09 11:47:12.205 | info | (24661) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason


</body>
</html>`
