### ISSUE TITLE
please make password 'invisible`

### ISSUE THREAD

**Issue by Homoran** [iobroker-community-adapters/ioBroker.synology#98]
As said, the password in the config is plain text.
This should be asterisks or anything like this

I hope teh oassword is not stored as plain text too

**Comment by Apollon77** [comment]
Which adapter version? The 1.0.0 of this adapter at least stores the password encrypted

**Comment by Homoran** [comment]
version 2.0.1
I don't know how it is stored, this just was a hint.

In the config of the instance it can be seen clearly written

**Comment by Apollon77** [comment]
SHould not ... plesse save settings again and check

**Comment by MC-1984** [comment]
Same problem here as well as with the 2FA Key. Saving adapter settings and reopening the settings again does not solve the issue.

**Comment by Apollon77** [comment]
Ok, the 2FA Key was NEVER encrypted ... so this would need to be added. But the password should be encrypted

**Comment by foxriver76** [comment]
It is not invisible because json config uses text. There was a bug but now it should work with password and repeat explicitly set

**Comment by foxriver76** [comment]
Please try gh version

**Comment by foxriver76** [comment]
Maybe needs admin Dep increase if we want to be exact

**Comment by Apollon77** [comment]
DO you kniow hcih admin is needed @foxriver76 ?

**Comment by foxriver76** [comment]
Unfortunately not, my source is only your comment https://github.com/ioBroker/ioBroker.admin/issues/1131#issuecomment-1062701132 but as synology already had the `repeat` arg I would assume that there was a partial fix in admin at some point

**Comment by Apollon77** [comment]
I added "repeat" there :-) but yes then no special admin dep is needed beside the one it will get because next update will get an update becaiuse 2FA code will also be encrypted :-) hence needs to be reentered

**Comment by foxriver76** [comment]
Perfect, then it should work now :+1:
